name: "Avx CLI"
description: "This action run a syntax validation using Avx CLI"
inputs: 
  paths: 
    description: "String with the paths to the files to be validated"
    required: true
  secret-input: 
     description: "Secrets"
     required: true
runs:
  using: composite
  steps: 
    - name: "Fetch Avx CLI"
      uses: actions/checkout@v2
      with: 
        ref: main
        repository: betrybe/avx-cli
        token: ${{ inputs.secret-input }}
    - run: ls
      shell: bash

    - name: "Setup Elixir"
      uses: erlef/setup-beam@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with: 
        elixir-version: "1.12.2"
        otp-version: "22.3"
    - run: ls
      shell: bash
    - run: mix deps.get
      shell: bash
    - run: mix release
      shell: bash
    - run: "alias avx=\"_build/prod/rel/bakeware/avx_cli\""
      shell: bash

    - id: syntax-check
    - run: cd
      shell: bash
    - run: echo avx syntax -f ${{ inputs.paths }}
      shell: bash