name: "Avx CLI"
description: "This action run a syntax validation using Avx CLI"
inputs: 
  paths: 
    description: "String with the paths to the files to be validated"
    required: true
  secret-input: 
     description: "Secrets"
     required: true
env:
    BAKEWARE_CACHE: /home/runner/work/quizzes/quizzes/.cache/bakeware
runs:
  using: composite
  steps: 
    - name: "Fetch Avx CLI"
      uses: actions/checkout@v2
      with: 
        repository: betrybe/avx-cli@0.0.68
        token: ${{ inputs.secret-input }}

    - name: "Setup Elixir"
      uses: erlef/setup-beam@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with: 
        elixir-version: "1.12.2"
        otp-version: "22.3"
    - run: mkdir -p /home/runner/work/quizzes/quizzes/.cache/bakeware/.tmp
      shell: bash
    - run: mix deps.get
      shell: bash
    - run: mix release
      shell: bash
    - run: alias avx="_build/prod/rel/bakeware/avx_cli"
      shell: bash
    - run: echo "$(_build/prod/rel/bakeware/avx_cli syntax -f "${{ inputs.paths }}")"
      shell: bash