name: "Avx CLI"
description: "This action run a syntax validation using Avx CLI"
inputs: 
  paths: 
    description: "String with the paths to the files to be validated"
    required: true
outputs: 
  syntax-check: 
    description: "Checks if the quiz file has some common .md syntax errors"
    value: "${{ steps.syntax-check.outputs }}"
runs:
  using: composite
  steps: 
    - name: "Fetch Avx CLI"
      uses: actions/checkout@v2
      with: 
        path: .github/actions/avx-cli
        ref: main
        repository: betrybe/avx-cli
        token: ${{ secrets.GIT_HUB_PAT }}

    - name: "Setup Elixir"
      shell: bash
      uses: erlef/setup-beam@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with: 
        elixir-version: "1.12.2"
        otp-version: "22.3"
      run: mix deps.get
      run: mix release
      run: "alias avx=\"_build/prod/rel/bakeware/avx_cli\""

    - name: "Run Avx CLI"
      id: syntax-check
      run: "echo avx syntax -f $PATHS"
      shell: bash
      env: 
        PATHS: ${{ inputs.paths }}